import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { Car, Calendar, CreditCard, User, Star } from 'lucide-react';
import DashboardCard from '../../shared/DashboardCard';
import { useCustomerData } from './useCustomerData';
const CustomerOverview = ({ onSectionChange }) => {
    const { customer, activeRentals, totalBookings, totalSpent, customerStats, recentBookings, availableCars // Get the calculated available cars from the hook
     } = useCustomerData();
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-md p-6", children: [_jsxs("h2", { className: "text-2xl font-bold text-gray-900 dark:text-white mb-2", children: ["Welcome back, ", customer?.name || 'User', "!"] }), _jsx("p", { className: "text-gray-600 dark:text-gray-400", children: "Here's an overview of your account and recent activity." })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-6", children: [_jsx(DashboardCard, { title: "Active Rentals", value: activeRentals, icon: Calendar }), _jsx(DashboardCard, { title: "Total Bookings", value: totalBookings, icon: Car }), _jsx(DashboardCard, { title: "Total Spent", value: `$${(Number(totalSpent) || 0).toFixed(2)}`, icon: CreditCard }), _jsx(DashboardCard, { title: "Available Cars", value: availableCars?.length || 0, icon: Car })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-md p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white mb-4", children: "Recent Bookings" }), _jsx("div", { className: "space-y-3", children: recentBookings.slice(0, 3).map(booking => (_jsxs("div", { className: "flex justify-between items-center p-3 bg-gray-50 dark:bg-gray-700 rounded-lg", children: [_jsxs("div", { children: [_jsxs("p", { className: "font-medium text-sm text-gray-900 dark:text-white", children: ["#", booking.id.toString().padStart(4, '0')] }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400", children: booking.carDetails }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400", children: booking.startDate })] }), _jsx("span", { className: `px-2 py-1 rounded-full text-xs font-medium ${booking.status === 'completed' ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400' :
                                                booking.status === 'active' ? 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400' :
                                                    'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400'}`, children: booking.status })] }, booking.id))) }), _jsx("button", { onClick: () => onSectionChange('bookings'), className: "mt-4 text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 text-sm font-medium", children: "View all bookings \u2192" })] }), _jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-md p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white mb-4", children: "Quick Actions" }), _jsxs("div", { className: "space-y-3", children: [_jsxs("button", { onClick: () => onSectionChange('browse-cars'), className: "w-full flex items-center p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg hover:bg-blue-100 dark:hover:bg-blue-900/30 transition-colors", children: [_jsx(Car, { className: "w-5 h-5 text-black dark:text-white mr-3" }), _jsx("span", { className: "text-black dark:text-white font-medium", children: "Browse Available Cars" })] }), _jsxs("button", { onClick: () => onSectionChange('bookings'), className: "w-full flex items-center p-3 bg-green-50 dark:bg-green-900/20 rounded-lg hover:bg-green-100 dark:hover:bg-green-900/30 transition-colors", children: [_jsx(Calendar, { className: "w-5 h-5 text-green-600 dark:text-green-400 mr-3" }), _jsx("span", { className: "text-green-600 dark:text-green-400 font-medium", children: "Manage Bookings" })] }), _jsxs("button", { onClick: () => onSectionChange('payments'), className: "w-full flex items-center p-3 bg-purple-50 dark:bg-purple-900/20 rounded-lg hover:bg-purple-100 dark:hover:bg-purple-900/30 transition-colors", children: [_jsx(CreditCard, { className: "w-5 h-5 text-purple-600 dark:text-purple-400 mr-3" }), _jsx("span", { className: "text-purple-600 dark:text-purple-400 font-medium", children: "Payment History" })] }), _jsxs("button", { onClick: () => onSectionChange('reviews'), className: "w-full flex items-center p-3 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg hover:bg-yellow-100 dark:hover:bg-yellow-900/30 transition-colors", children: [_jsx(Star, { className: "w-5 h-5 text-yellow-600 dark:text-yellow-400 mr-3" }), _jsx("span", { className: "text-yellow-600 dark:text-yellow-400 font-medium", children: "My Reviews" })] }), _jsxs("button", { onClick: () => onSectionChange('profile'), className: "w-full flex items-center p-3 bg-orange-50 dark:bg-orange-900/20 rounded-lg hover:bg-orange-100 dark:hover:bg-orange-900/30 transition-colors", children: [_jsx(User, { className: "w-5 h-5 text-orange-600 dark:text-orange-400 mr-3" }), _jsx("span", { className: "text-orange-600 dark:text-orange-400 font-medium", children: "Update Profile" })] })] })] })] })] }));
};
export default CustomerOverview;
