import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React, { useState, useMemo } from 'react';
import { FaEye, FaEdit, FaTrash, FaSearch, FaFilter, FaChevronLeft, FaChevronRight, FaCar, FaWrench, FaCheck } from 'react-icons/fa';
import { format } from 'date-fns';
import MaintenanceStatusBadge from './MaintenanceStatusBadge';
const MaintenanceTable = ({ maintenanceRecords, loading = false, onEdit, onDelete, onViewDetails, onMarkCompleted, updating = {} }) => {
    const [searchTerm, setSearchTerm] = useState('');
    const [typeFilter, setTypeFilter] = useState('all');
    const [statusFilter, setStatusFilter] = useState('all');
    const [currentPage, setCurrentPage] = useState(1);
    const [pageSize] = useState(10);
    // Filter and search maintenance records
    const filteredRecords = useMemo(() => {
        return maintenanceRecords.filter(record => {
            const matchesSearch = record.car.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                record.car.model.toLowerCase().includes(searchTerm.toLowerCase()) ||
                record.car.make.toLowerCase().includes(searchTerm.toLowerCase()) ||
                record.type.toLowerCase().includes(searchTerm.toLowerCase()) ||
                record.description.toLowerCase().includes(searchTerm.toLowerCase());
            const matchesType = typeFilter === 'all' || record.type === typeFilter;
            const matchesStatus = statusFilter === 'all' || record.status === statusFilter;
            return matchesSearch && matchesType && matchesStatus;
        });
    }, [maintenanceRecords, searchTerm, typeFilter, statusFilter]);
    // Pagination
    const totalPages = Math.ceil(filteredRecords.length / pageSize);
    const startIndex = (currentPage - 1) * pageSize;
    const paginatedRecords = filteredRecords.slice(startIndex, startIndex + pageSize);
    // Reset to first page when filters change
    React.useEffect(() => {
        setCurrentPage(1);
    }, [searchTerm, typeFilter, statusFilter]);
    const formatDate = (dateString) => {
        if (!dateString)
            return '—';
        return format(new Date(dateString), 'MMM d, yyyy');
    };
    const getMaintenanceTypeIcon = (type) => {
        switch (type) {
            case 'routine': return FaWrench;
            case 'repair': return FaCar;
            case 'inspection': return FaEye;
            case 'emergency': return FaCheck;
            default: return FaWrench;
        }
    };
    const typeOptions = [
        { value: 'all', label: 'All Types' },
        { value: 'routine', label: 'Routine' },
        { value: 'repair', label: 'Repair' },
        { value: 'inspection', label: 'Inspection' },
        { value: 'emergency', label: 'Emergency' }
    ];
    const statusOptions = [
        { value: 'all', label: 'All Status' },
        { value: 'scheduled', label: 'Scheduled' },
        { value: 'in-progress', label: 'In Progress' },
        { value: 'completed', label: 'Completed' },
        { value: 'cancelled', label: 'Cancelled' }
    ];
    if (loading) {
        return (_jsx("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700", children: _jsx("div", { className: "p-6", children: _jsx("div", { className: "animate-pulse space-y-4", children: [...Array(5)].map((_, index) => (_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("div", { className: "w-16 h-16 bg-gray-200 dark:bg-gray-700 rounded-lg" }), _jsxs("div", { className: "flex-1 space-y-2", children: [_jsx("div", { className: "h-4 bg-gray-200 dark:bg-gray-700 rounded w-3/4" }), _jsx("div", { className: "h-3 bg-gray-200 dark:bg-gray-700 rounded w-1/2" })] }), _jsx("div", { className: "w-20 h-6 bg-gray-200 dark:bg-gray-700 rounded" })] }, index))) }) }) }));
    }
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-4", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "relative w-full", children: [_jsx(FaSearch, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 text-sm" }), _jsx("input", { type: "text", placeholder: "Search by car, maintenance type, or description...", value: searchTerm, onChange: (e) => setSearchTerm(e.target.value), className: "w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:ring-2 focus:ring-blue-500 focus:border-transparent" })] }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-2 items-start sm:items-center", children: [_jsxs("div", { className: "flex items-center gap-2 text-gray-400 text-sm", children: [_jsx(FaFilter, {}), _jsx("span", { className: "hidden sm:inline", children: "Filters:" })] }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-2 w-full sm:w-auto", children: [_jsx("select", { value: typeFilter, onChange: (e) => setTypeFilter(e.target.value), className: "w-full sm:w-auto px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm", children: typeOptions.map((option) => (_jsx("option", { value: option.value, children: option.label }, option.value))) }), _jsx("select", { value: statusFilter, onChange: (e) => setStatusFilter(e.target.value), className: "w-full sm:w-auto px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm", children: statusOptions.map((option) => (_jsx("option", { value: option.value, children: option.label }, option.value))) })] })] })] }), _jsxs("div", { className: "mt-4 text-sm text-gray-600 dark:text-gray-400", children: ["Showing ", paginatedRecords.length, " of ", filteredRecords.length, " maintenance records"] })] }), _jsx("div", { className: "bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden", children: paginatedRecords.length === 0 ? (_jsxs("div", { className: "p-12 text-center", children: [_jsx("div", { className: "mx-auto w-16 h-16 bg-gray-100 dark:bg-gray-700 rounded-full flex items-center justify-center mb-4", children: _jsx(FaWrench, { className: "text-2xl text-gray-400" }) }), _jsx("h3", { className: "text-lg font-medium text-gray-900 dark:text-white mb-2", children: "No maintenance records found" }), _jsx("p", { className: "text-gray-500 dark:text-gray-400", children: searchTerm || typeFilter !== 'all' || statusFilter !== 'all'
                                ? 'Try adjusting your search or filter criteria.'
                                : 'No maintenance records available at the moment.' })] })) : (_jsxs(_Fragment, { children: [_jsx("div", { className: "hidden lg:block overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-gray-50 dark:bg-gray-700", children: _jsxs("tr", { children: [_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider", children: "Car" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider", children: "Maintenance Type" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider", children: "Description" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider", children: "Date Scheduled" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider", children: "Status" }), _jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider", children: "Actions" })] }) }), _jsx("tbody", { className: "bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700", children: paginatedRecords.map((record) => {
                                            const TypeIcon = getMaintenanceTypeIcon(record.type);
                                            return (_jsxs("tr", { className: "hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors", children: [_jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("img", { src: record.car.imageUrl || 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiBmaWxsPSIjMzc0MTUxIi8+CjxwYXRoIGQ9Ik0xNiAyNEg0OEw0NiAzNkg0MFYzMkgzNlYzNkgzMFYzMkgyNlYzNkgyMFYzMkgxOFYzNkgxNkwyNCAyNFoiIGZpbGw9IiNGRkZGRkYiLz4KPHN2Zz4K', alt: `${record.car.make} ${record.car.model}`, className: "w-12 h-12 rounded-lg object-cover", onError: (e) => {
                                                                        e.currentTarget.src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiBmaWxsPSIjMzc0MTUxIi8+CjxwYXRoIGQ9Ik0xNiAyNEg0OEw0NiAzNkg0MFYzMkgzNlYzNkgzMFYzMkgyNlYzNkgyMFYzMkgxOFYzNkgxNkwyNCAyNFoiIGZpbGw9IiNGRkZGRkYiLz4KPHN2Zz4K';
                                                                    } }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium text-gray-900 dark:text-white", children: record.car.name }), _jsxs("div", { className: "text-sm text-gray-500 dark:text-gray-400", children: [record.car.make, " ", record.car.model, " (", record.car.year, ")"] })] })] }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(TypeIcon, { className: "w-4 h-4 text-gray-400" }), _jsx("span", { className: "text-sm font-medium text-gray-900 dark:text-white capitalize", children: record.type.replace('_', ' ') })] }) }), _jsx("td", { className: "px-6 py-4", children: _jsx("div", { className: "text-sm text-gray-900 dark:text-white max-w-xs truncate", children: record.description }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsx("div", { className: "text-sm text-gray-900 dark:text-white", children: formatDate(record.scheduledDate) }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsx(MaintenanceStatusBadge, { status: record.status, priority: record.priority, size: "sm" }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("button", { onClick: () => onViewDetails(record), className: "p-2 text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-colors", title: "View Details", children: _jsx(FaEye, { className: "w-4 h-4" }) }), _jsx("button", { onClick: () => onEdit(record), className: "p-2 text-yellow-600 hover:text-yellow-800 dark:text-yellow-400 dark:hover:text-yellow-300 hover:bg-yellow-50 dark:hover:bg-yellow-900/20 rounded-lg transition-colors", title: "Edit Maintenance", children: _jsx(FaEdit, { className: "w-4 h-4" }) }), record.status === 'scheduled' && (_jsx("button", { onClick: () => onMarkCompleted(record.id), disabled: updating[record.id.toString()], className: "p-2 text-green-600 hover:text-green-800 dark:text-green-400 dark:hover:text-green-300 hover:bg-green-50 dark:hover:bg-green-900/20 rounded-lg transition-colors disabled:opacity-50", title: "Mark as Completed", children: _jsx(FaCheck, { className: "w-4 h-4" }) })), _jsx("button", { onClick: () => onDelete(record.id), disabled: updating[record.id.toString()], className: "p-2 text-red-600 hover:text-red-800 dark:text-red-400 dark:hover:text-red-300 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors disabled:opacity-50", title: "Delete Maintenance", children: _jsx(FaTrash, { className: "w-4 h-4" }) })] }) })] }, record.id));
                                        }) })] }) }), _jsx("div", { className: "lg:hidden divide-y divide-gray-200 dark:divide-gray-700", children: paginatedRecords.map((record) => {
                                const TypeIcon = getMaintenanceTypeIcon(record.type);
                                return (_jsxs("div", { className: "p-4 space-y-4", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex items-start space-x-3 flex-1", children: [_jsx("img", { src: record.car.imageUrl || 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiBmaWxsPSIjMzc0MTUxIi8+CjxwYXRoIGQ9Ik0xNiAyNEg0OEw0NiAzNkg0MFYzMkgzNlYzNkgzMFYzMkgyNlYzNkgyMFYzMkgxOFYzNkgxNkwyNCAyNFoiIGZpbGw9IiNGRkZGRkYiLz4KPHN2Zz4K', alt: `${record.car.make} ${record.car.model}`, className: "w-12 h-12 rounded-lg object-cover flex-shrink-0", onError: (e) => {
                                                                e.currentTarget.src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiBmaWxsPSIjMzc0MTUxIi8+CjxwYXRoIGQ9Ik0xNiAyNEg0OEw0NiAzNkg0MFYzMkgzNlYzNkgzMFYzMkgyNlYzNkgyMFYzMkgxOFYzNkgxNkwyNCAyNFoiIGZpbGw9IiNGRkZGRkYiLz4KPHN2Zz4K';
                                                            } }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("div", { className: "text-sm font-medium text-gray-900 dark:text-white", children: record.car.name }), _jsxs("div", { className: "text-sm text-gray-500 dark:text-gray-400", children: [record.car.make, " ", record.car.model, " (", record.car.year, ")"] }), _jsxs("div", { className: "flex items-center space-x-2 mt-1", children: [_jsx(TypeIcon, { className: "w-4 h-4 text-gray-400" }), _jsx("span", { className: "text-sm text-gray-600 dark:text-gray-300 capitalize", children: record.type.replace('_', ' ') })] })] })] }), _jsx(MaintenanceStatusBadge, { status: record.status, priority: record.priority, size: "sm" })] }), _jsxs("div", { className: "space-y-2 text-sm", children: [_jsxs("div", { children: [_jsx("div", { className: "text-gray-500 dark:text-gray-400", children: "Description" }), _jsx("div", { className: "text-gray-900 dark:text-white", children: record.description })] }), _jsxs("div", { children: [_jsx("div", { className: "text-gray-500 dark:text-gray-400", children: "Scheduled Date" }), _jsx("div", { className: "text-gray-900 dark:text-white", children: formatDate(record.scheduledDate) })] })] }), _jsxs("div", { className: "flex items-center justify-end space-x-2 pt-2 border-t border-gray-200 dark:border-gray-700", children: [_jsxs("button", { onClick: () => onViewDetails(record), className: "px-3 py-2 text-sm text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-colors flex items-center space-x-1", children: [_jsx(FaEye, { className: "w-4 h-4" }), _jsx("span", { children: "View" })] }), _jsxs("button", { onClick: () => onEdit(record), className: "px-3 py-2 text-sm text-yellow-600 hover:text-yellow-800 dark:text-yellow-400 dark:hover:text-yellow-300 hover:bg-yellow-50 dark:hover:bg-yellow-900/20 rounded-lg transition-colors flex items-center space-x-1", children: [_jsx(FaEdit, { className: "w-4 h-4" }), _jsx("span", { children: "Edit" })] }), record.status === 'scheduled' && (_jsxs("button", { onClick: () => onMarkCompleted(record.id), disabled: updating[record.id.toString()], className: "px-3 py-2 text-sm text-green-600 hover:text-green-800 dark:text-green-400 dark:hover:text-green-300 hover:bg-green-50 dark:hover:bg-green-900/20 rounded-lg transition-colors disabled:opacity-50 flex items-center space-x-1", children: [_jsx(FaCheck, { className: "w-4 h-4" }), _jsx("span", { children: "Complete" })] })), _jsxs("button", { onClick: () => onDelete(record.id), disabled: updating[record.id.toString()], className: "px-3 py-2 text-sm text-red-600 hover:text-red-800 dark:text-red-400 dark:hover:text-red-300 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors disabled:opacity-50 flex items-center space-x-1", children: [_jsx(FaTrash, { className: "w-4 h-4" }), _jsx("span", { children: "Delete" })] })] })] }, record.id));
                            }) }), totalPages > 1 && (_jsx("div", { className: "px-4 sm:px-6 py-4 border-t border-gray-200 dark:border-gray-700", children: _jsxs("div", { className: "flex flex-col sm:flex-row items-center justify-between gap-4", children: [_jsxs("div", { className: "text-sm text-gray-700 dark:text-gray-300 order-2 sm:order-1", children: [_jsxs("span", { className: "hidden sm:inline", children: ["Showing ", startIndex + 1, " to ", Math.min(startIndex + pageSize, filteredRecords.length), " of ", filteredRecords.length, " results"] }), _jsxs("span", { className: "sm:hidden", children: [startIndex + 1, "-", Math.min(startIndex + pageSize, filteredRecords.length), " of ", filteredRecords.length] })] }), _jsxs("div", { className: "flex items-center space-x-2 order-1 sm:order-2", children: [_jsx("button", { onClick: () => setCurrentPage(prev => Math.max(prev - 1, 1)), disabled: currentPage === 1, className: "p-2 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 disabled:opacity-50 disabled:cursor-not-allowed", children: _jsx(FaChevronLeft, { className: "w-4 h-4" }) }), _jsx("div", { className: "flex items-center space-x-1", children: [...Array(totalPages)].map((_, index) => {
                                                    const page = index + 1;
                                                    const isCurrentPage = page === currentPage;
                                                    // Show fewer pages on mobile
                                                    const isMobile = typeof window !== 'undefined' && window.innerWidth < 640;
                                                    const showPage = isMobile
                                                        ? (page === 1 || page === totalPages || page === currentPage)
                                                        : (page === 1 || page === totalPages || Math.abs(page - currentPage) <= 1);
                                                    if (!showPage && page !== 2 && page !== totalPages - 1) {
                                                        return page === 2 || page === totalPages - 1 ? (_jsx("span", { className: "px-2 text-gray-500 hidden sm:inline", children: "..." }, page)) : null;
                                                    }
                                                    return (_jsx("button", { onClick: () => setCurrentPage(page), className: `px-3 py-1 text-sm rounded-md ${isCurrentPage
                                                            ? 'bg-blue-600 text-white'
                                                            : 'text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700'}`, children: page }, page));
                                                }) }), _jsx("button", { onClick: () => setCurrentPage(prev => Math.min(prev + 1, totalPages)), disabled: currentPage === totalPages, className: "p-2 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 disabled:opacity-50 disabled:cursor-not-allowed", children: _jsx(FaChevronRight, { className: "w-4 h-4" }) })] })] }) }))] })) })] }));
};
export default MaintenanceTable;
