import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import useReduxAuth from "../store/hooks/useReduxAuth";
import { FaCar, FaUsers, FaChartBar } from "react-icons/fa";
const RoleTest = () => {
    const { user, logout } = useReduxAuth();
    const isAdmin = user?.role === "admin";
    const isOwner = user?.role === "owner";
    const isCustomer = user?.role === "customer";
    const renderRoleContent = () => {
        if (!user) {
            return (_jsxs("div", { className: "text-center", children: [_jsx("h2", { className: "text-2xl font-bold mb-4", children: "Please login to see your role" }), _jsx("p", { className: "text-gray-600", children: "You can login as a customer, owner, or admin" })] }));
        }
        return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "text-center", children: [_jsxs("h2", { className: "text-2xl font-bold mb-4", children: ["Hello, ", user.name] }), _jsxs("p", { className: "text-gray-600", children: ["Your role is: ", user.role] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6", children: [isCustomer && (_jsxs("div", { className: "bg-blue-50 p-6 rounded-lg shadow", children: [_jsx(FaCar, { className: "w-8 h-8 text-blue-500 mb-4" }), _jsx("h3", { className: "text-lg font-semibold mb-2", children: "Customer Features" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { className: "text-gray-600", children: "Browse and rent cars" }), _jsx("li", { className: "text-gray-600", children: "Write reviews" }), _jsx("li", { className: "text-gray-600", children: "Like cars" }), _jsx("li", { className: "text-gray-600", children: "View your rentals" })] })] })), isOwner && (_jsxs("div", { className: "bg-green-50 p-6 rounded-lg shadow", children: [_jsx(FaCar, { className: "w-8 h-8 text-green-500 mb-4" }), _jsx("h3", { className: "text-lg font-semibold mb-2", children: "Owner Features" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { className: "text-gray-600", children: "List your cars" }), _jsx("li", { className: "text-gray-600", children: "Manage your listings" }), _jsx("li", { className: "text-gray-600", children: "View rental history" })] })] })), isAdmin && (_jsxs("div", { className: "bg-red-50 p-6 rounded-lg shadow", children: [_jsx(FaUsers, { className: "w-8 h-8 text-red-500 mb-4" }), _jsx("h3", { className: "text-lg font-semibold mb-2", children: "Admin Features" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { className: "text-gray-600", children: "Manage all users" }), _jsx("li", { className: "text-gray-600", children: "View statistics" }), _jsx("li", { className: "text-gray-600", children: "Manage rentals" })] })] })), _jsxs("div", { className: "bg-gray-50 p-6 rounded-lg shadow", children: [_jsx(FaChartBar, { className: "w-8 h-8 text-gray-500 mb-4" }), _jsx("h3", { className: "text-lg font-semibold mb-2", children: "Common Features" }), _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { className: "text-gray-600", children: "View car listings" }), _jsx("li", { className: "text-gray-600", children: "Search cars" })] })] })] }), _jsx("button", { onClick: logout, className: "bg-red-500 text-white px-6 py-2 rounded-lg hover:bg-red-600 transition-colors", children: "Logout" })] }));
    };
    return (_jsx("div", { className: "container mx-auto px-4 py-8", children: renderRoleContent() }));
};
export default RoleTest;
