import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { X, AlertTriangle } from 'lucide-react';
const DeleteConfirmationModal = ({ isOpen, onClose, onConfirm, car, isDeleting = false }) => {
    if (!isOpen || !car)
        return null;
    return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-3 sm:p-4", children: _jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-lg p-4 sm:p-6 w-full max-w-sm sm:max-w-md", children: [_jsxs("div", { className: "flex justify-between items-start mb-4", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 bg-red-100 dark:bg-red-900 rounded-full flex items-center justify-center", children: _jsx(AlertTriangle, { className: "w-4 h-4 sm:w-5 sm:h-5 text-red-600 dark:text-red-400" }) }), _jsx("h2", { className: "text-base sm:text-lg font-semibold text-gray-900 dark:text-white", children: "Delete Car" })] }), _jsx("button", { onClick: onClose, disabled: isDeleting, className: "text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 disabled:opacity-50 p-1", children: _jsx(X, { className: "w-4 h-4 sm:w-5 sm:h-5" }) })] }), _jsxs("div", { className: "mb-6", children: [_jsx("p", { className: "text-gray-700 dark:text-gray-300 mb-4", children: "Are you sure you want to delete this car? This action cannot be undone." }), _jsx("div", { className: "bg-gray-50 dark:bg-gray-700 rounded-lg p-3 sm:p-4", children: _jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("img", { src: car.imageUrl || '/placeholder-car.jpg', alt: car.model, className: "w-12 h-12 sm:w-16 sm:h-16 rounded-lg object-cover flex-shrink-0", onError: (e) => {
                                            e.target.src = '/placeholder-car.jpg';
                                        } }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("p", { className: "font-medium text-gray-900 dark:text-white text-sm sm:text-base truncate", children: [car.year, " ", car.make, " ", car.model] }), _jsx("p", { className: "text-xs sm:text-sm text-gray-500 dark:text-gray-400 truncate", children: car.name }), _jsxs("p", { className: "text-xs sm:text-sm text-gray-500 dark:text-gray-400", children: ["$", car.rentalPricePerDay, "/day"] })] })] }) })] }), _jsxs("div", { className: "flex flex-col sm:flex-row justify-end gap-3", children: [_jsx("button", { type: "button", onClick: onClose, disabled: isDeleting, className: "w-full sm:w-auto px-4 py-2 text-gray-700 dark:text-gray-300 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed order-2 sm:order-1", children: "Cancel" }), _jsx("button", { type: "button", onClick: onConfirm, disabled: isDeleting, className: "w-full sm:w-auto px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center space-x-2 order-1 sm:order-2", children: isDeleting ? (_jsxs(_Fragment, { children: [_jsx("div", { className: "w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" }), _jsx("span", { children: "Deleting..." })] })) : (_jsx("span", { children: "Delete Car" })) })] })] }) }));
};
export default DeleteConfirmationModal;
